/**
 * GET /api/v1/chats/:sessionId/export?format=md|json — export chat + citations (spec §2.4)
 */
import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getCurrentUser } from '@/server/bootstrap';
import { recordAudit } from '@/server/audit';
import { DigestNoteContentSchema } from '@/lib/types';

export const dynamic = 'force-dynamic';

interface CitationJson {
  documentId: string;
  documentTitle: string;
  pageNumber: number;
  snippet: string;
  score: number;
}

export async function GET(
  request: Request,
  ctx: { params: Promise<{ sessionId: string }> },
) {
  try {
    const { sessionId } = await ctx.params;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') === 'json' ? 'json' : 'md';

    const user = await getCurrentUser();
    const session = await db.chatSession.findUnique({
      where: { id: sessionId },
      include: {
        workspace: { include: { members: { where: { userId: user.id } } } },
        messages: { orderBy: { createdAt: 'asc' } },
      },
    });
    if (!session || session.workspace.members.length === 0) {
      return NextResponse.json({ error: 'Chat session not found or access denied' }, { status: 404 });
    }

    const turns = session.messages.map((m) => ({
      role: m.role,
      content: m.content,
      citations: (m.citationsJson ? safeParseArray(m.citationsJson) : []) as CitationJson[],
      tokenUsage: m.tokenUsage,
      feedback: m.feedback === 'UP' || m.feedback === 'DOWN' ? m.feedback : null,
      createdAt: m.createdAt.toISOString(),
    }));

    await recordAudit({
      workspaceId: session.workspaceId,
      actorEmail: user.email,
      action: 'export.create',
      targetType: 'chat',
      targetId: sessionId,
      detail: { format },
    });

    if (format === 'json') {
      const payload = {
        exportedAt: new Date().toISOString(),
        session: { id: session.id, title: session.title, workspaceId: session.workspaceId },
        turns,
      };
      return new NextResponse(JSON.stringify(payload, null, 2), {
        headers: {
          'Content-Type': 'application/json',
          'Content-Disposition': `attachment; filename="insightdoc-chat-${sessionId.slice(0, 8)}.json"`,
        },
      });
    }

    // Markdown report
    const lines: string[] = [
      `# InsightDoc Chat Report`,
      ``,
      `- **Session:** ${session.title}`,
      `- **Workspace:** ${session.workspace.name}`,
      `- **Exported:** ${new Date().toISOString()}`,
      `- **Turns:** ${turns.length}`,
      ``,
      `---`,
      ``,
    ];
    for (const turn of turns) {
      const rating = turn.feedback === 'UP' ? ' 👍' : turn.feedback === 'DOWN' ? ' 👎' : '';

      // Shared digest notes render as structured sections, not raw JSON.
      if (turn.role === 'note') {
        const note = DigestNoteContentSchema.safeParse(safeParseObject(turn.content));
        lines.push(`### 📋 Shared AI digest — ${note.success ? note.data.documentTitle : 'note'}`);
        lines.push(``);
        if (note.success) {
          const d = note.data.digest;
          lines.push(d.overview);
          lines.push(``);
          lines.push(`**Key points:**`);
          for (const k of d.keyPoints) lines.push(`- ${k}`);
          if (d.entities.length > 0) {
            lines.push(``);
            lines.push(`**Entities:** ${d.entities.join(', ')}`);
          }
          if (d.suggestedQuestions.length > 0) {
            lines.push(``);
            lines.push(`**Suggested questions:**`);
            for (const q of d.suggestedQuestions) lines.push(`- ${q}`);
          }
          lines.push(``);
          lines.push(`> Generated by ${note.data.model} · ${new Date(note.data.generatedAt).toLocaleString()}`);
        } else {
          lines.push(turn.content); // corrupt payload — export verbatim
        }
        lines.push(``);
        continue;
      }

      lines.push(`### ${turn.role === 'user' ? '🧑 Question' : '🤖 InsightDoc'}${rating}`);
      lines.push(``);
      lines.push(turn.content);
      if (turn.citations.length > 0) {
        lines.push(``);
        lines.push(`**Sources:**`);
        for (const [i, c] of turn.citations.entries()) {
          lines.push(`${i + 1}. ${c.documentTitle}, p.${c.pageNumber} (score ${c.score.toFixed(2)}): "${c.snippet.slice(0, 180)}${c.snippet.length > 180 ? '…' : ''}"`);
        }
      }
      lines.push(``);
    }

    return new NextResponse(lines.join('\n'), {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="insightdoc-chat-${sessionId.slice(0, 8)}.md"`,
      },
    });
  } catch (error) {
    console.error('[GET /chats/:id/export]', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}

function safeParseArray(json: string): unknown[] {
  try {
    const parsed: unknown = JSON.parse(json);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function safeParseObject(json: string): unknown {
  try {
    return JSON.parse(json);
  } catch {
    return null;
  }
}
