'use client';

/**
 * InsightDoc — Document Detail Dialog
 * Metadata summary + AI digest card + paginated chunk inspector: shows what
 * the vector index holds per document (heading, page, tokens, preview) and a
 * grounded LLM digest (overview, key points, entities, suggested questions).
 */
import { useEffect, useState } from 'react';
import {
  BadgeCheck,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Copy,
  FileText,
  Layers,
  Loader2,
  MapPin,
  CircleQuestionMark,
  MessageSquare,
  MessageSquarePlus,
  Pencil,
  RefreshCw,
  ScanLine,
  Send,
  Sparkles,
  Star,
} from 'lucide-react';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';
import { formatBytes } from '@/lib/types';
import type { ChunkPreview, DocumentChunksResponse, DocumentSummaryResponse } from '@/lib/types';
import { useAppStore } from './store';
import { TagEditor } from './tag-editor';
import { fetchDocumentChunks, fetchDocumentSummary, generateDocumentSummary, renameDocument, shareDigestToChat } from './api-client';

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60_000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return new Date(iso).toLocaleDateString();
}

function digestToMarkdown(title: string, d: DocumentSummaryResponse): string {
  const s = d.summary;
  return [
    `# AI digest — ${title}`,
    '',
    s.overview,
    '',
    '## Key points',
    ...s.keyPoints.map((k) => `- ${k}`),
    '',
    '## Entities',
    s.entities.join(', '),
    '',
    '## Suggested questions',
    ...s.suggestedQuestions.map((q) => `- ${q}`),
    '',
    `---\nGenerated by ${d.model} · ${new Date(d.generatedAt).toLocaleString()} · grounded in ${d.basis.chunkCount} chunks`,
  ].join('\n');
}

/** Grounded AI digest card — cached on the server, regenerated on demand. */
function DigestSection({ documentId, title, indexed }: { documentId: string; title: string; indexed: boolean }) {
  const setDetailDocumentId = useAppStore((s) => s.setDetailDocumentId);
  const prefillComposer = useAppStore((s) => s.prefillComposer);
  const activeChatId = useAppStore((s) => s.activeChatId);
  const chats = useAppStore((s) => s.chats);
  const [summary, setSummary] = useState<DocumentSummaryResponse | null>(null);
  const [checked, setChecked] = useState(false); // initial cache lookup done?
  const [generating, setGenerating] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const activeChat = activeChatId ? chats.find((c) => c.id === activeChatId) ?? null : null;

  useEffect(() => {
    let cancelled = false;
    setSummary(null);
    setChecked(false);
    setError(null);
    fetchDocumentSummary(documentId)
      .then((s) => !cancelled && setSummary(s))
      .catch((e) => !cancelled && setError(e instanceof Error ? e.message : 'Failed to load digest'))
      .finally(() => !cancelled && setChecked(true));
    return () => {
      cancelled = true;
    };
  }, [documentId]);

  const runGenerate = async (force: boolean) => {
    setGenerating(true);
    setError(null);
    try {
      const next = await generateDocumentSummary(documentId, force);
      setSummary(next);
      toast.success(force ? 'Digest regenerated' : 'Digest ready');
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Digest failed';
      setError(msg);
      toast.error(msg);
    } finally {
      setGenerating(false);
    }
  };

  const copyDigest = async () => {
    if (!summary) return;
    const md = digestToMarkdown(title, summary);
    try {
      await navigator.clipboard.writeText(md);
      toast.success('Digest copied as Markdown');
    } catch {
      const ta = document.createElement('textarea');
      ta.value = md;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      ta.remove();
      toast.success('Digest copied as Markdown');
    }
  };

  const askQuestion = (q: string) => {
    setDetailDocumentId(null);
    prefillComposer(`About "${title}": ${q}`, { switchToChat: true });
  };

  /** Post the cached digest into a chat as a note card, then jump there. */
  const shareToChat = async (targetChatId?: string) => {
    if (!summary || sharing) return;
    setSharing(true);
    try {
      const res = await shareDigestToChat(documentId, targetChatId);
      const store = useAppStore.getState();
      const sharingIntoActiveChat =
        !res.createdChat && store.activeChatId === res.chat.id;
      store.upsertChat(res.chat);
      store.setActiveChat(res.chat.id);
      if (sharingIntoActiveChat && store.messages.length > 0) {
        // Keep the visible history — the note appends to the live conversation.
        store.appendMessage(res.message);
      } else {
        // Fresh chat — seed optimistically; ChatPanel refetches on activation.
        store.setMessages([res.message]);
      }
      store.setDetailDocumentId(null);
      store.setView('chat');
      toast.success(
        res.createdChat
          ? `Digest posted to a new chat — “${res.chat.title}”`
          : `Digest posted to “${res.chat.title}”`,
        { icon: '📋' },
      );
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Could not share the digest');
    } finally {
      setSharing(false);
    }
  };

  /** Header share control — dropdown when a chat is active (choose target), direct share otherwise. */
  const shareControl = (() => {
    const trigger = (onClick: () => void, title: string) => (
      <Button
        variant="ghost"
        size="icon"
        className="digest-share-btn h-6 w-6"
        disabled={sharing}
        onClick={onClick}
        aria-label="Share digest to chat"
        title={title}
      >
        {sharing ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
      </Button>
    );
    if (!activeChat) {
      return trigger(
        () => void shareToChat(),
        'Share to chat — posts this digest as a note in a new conversation',
      );
    }
    return (
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          {trigger(() => {}, 'Share to chat — pick the current conversation or a new one')}
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-60">
          <DropdownMenuItem className="gap-2" onClick={() => void shareToChat(activeChat.id)}>
            <MessageSquare className="h-3.5 w-3.5 text-primary" />
            <span className="flex min-w-0 flex-col">
              <span className="text-xs font-medium">Share into current chat</span>
              <span className="truncate text-[11px] text-muted-foreground">{activeChat.title}</span>
            </span>
          </DropdownMenuItem>
          <DropdownMenuItem className="gap-2" onClick={() => void shareToChat()}>
            <MessageSquarePlus className="h-3.5 w-3.5 text-cyan-500" />
            <span className="flex min-w-0 flex-col">
              <span className="text-xs font-medium">Share into a new chat</span>
              <span className="truncate text-[11px] text-muted-foreground">Digest — {title}</span>
            </span>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    );
  })();

  return (
    <div className="digest-card overflow-hidden rounded-xl border bg-gradient-to-b from-primary/[0.05] to-transparent">
      <div className="flex items-center gap-2 border-b bg-card/60 px-3 py-2">
        <span className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-primary/25 to-cyan-500/10">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
        </span>
        <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">AI digest</span>
        {summary && !generating && (
          <div className="ml-auto flex items-center gap-0.5">
            {shareControl}
            <Button
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              onClick={() => void copyDigest()}
              aria-label="Copy digest as Markdown"
              title="Copy as Markdown"
            >
              <Copy className="h-3 w-3" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              disabled={generating}
              onClick={() => void runGenerate(true)}
              aria-label="Regenerate digest"
              title="Regenerate"
            >
              <RefreshCw className="h-3 w-3" />
            </Button>
          </div>
        )}
      </div>

      <div className="p-3">
        {generating && (
          <div className="space-y-2.5" aria-live="polite">
            <p className="flex items-center gap-2 text-xs text-primary">
              <Loader2 className="h-3.5 w-3.5 animate-spin" /> Reading the indexed chunks and writing the digest…
            </p>
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-11/12" />
            <Skeleton className="h-3 w-4/5" />
            <div className="grid grid-cols-2 gap-2 pt-1">
              <Skeleton className="h-9" />
              <Skeleton className="h-9" />
            </div>
          </div>
        )}

        {!generating && error && (
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs text-destructive">{error}</p>
            <Button variant="outline" size="sm" className="h-7 shrink-0 text-xs" onClick={() => void runGenerate(Boolean(summary))}>
              Retry
            </Button>
          </div>
        )}

        {!generating && !error && !summary && checked && (
          <div className="flex flex-col items-center gap-2 rounded-lg border border-dashed p-4 text-center">
            <BadgeCheck className="h-5 w-5 text-primary/60" />
            <p className="text-xs text-muted-foreground">
              {indexed
                ? 'Generate a grounded summary — key points, entities and suggested questions, all traceable to the indexed chunks.'
                : 'Digests become available once the document is indexed.'}
            </p>
            <Button
              size="sm"
              className="h-7 gap-1.5 text-xs"
              disabled={!indexed || generating}
              onClick={() => void runGenerate(false)}
            >
              <Sparkles className="h-3 w-3" /> Generate digest
            </Button>
          </div>
        )}

        {!generating && !error && summary && (
          <div className="space-y-3">
            <p className="text-xs leading-relaxed text-foreground/90">{summary.summary.overview}</p>

            <div>
              <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Key points</p>
              <ul className="space-y-1">
                {summary.summary.keyPoints.map((k, i) => (
                  <li key={`kp-${i}`} className="flex items-start gap-1.5 text-xs leading-relaxed">
                    <CheckCircle2 className="mt-0.5 h-3 w-3 shrink-0 text-emerald-500" aria-hidden />
                    <span>{k}</span>
                  </li>
                ))}
              </ul>
            </div>

            {summary.summary.entities.length > 0 && (
              <div>
                <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Entities</p>
                <div className="flex flex-wrap gap-1">
                  {summary.summary.entities.map((e, i) => (
                    <Badge
                      key={`ent-${i}`}
                      variant="outline"
                      className="border-primary/25 bg-primary/5 px-1.5 py-0 text-[10px] font-normal text-primary/90"
                    >
                      {e}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {summary.summary.suggestedQuestions.length > 0 && (
              <div>
                <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Ask next</p>
                <div className="space-y-1">
                  {summary.summary.suggestedQuestions.map((q, i) => (
                    <button
                      key={`sq-${i}`}
                      onClick={() => askQuestion(q)}
                      className="group flex w-full items-center gap-1.5 rounded-lg border bg-card px-2 py-1.5 text-left text-xs transition hover:border-primary/40 hover:bg-primary/5"
                    >
                      <CircleQuestionMark className="h-3 w-3 shrink-0 text-primary/70" aria-hidden />
                      <span className="min-w-0 flex-1 truncate">{q}</span>
                      <span className="shrink-0 text-[10px] text-muted-foreground opacity-0 transition group-hover:opacity-100">Ask →</span>
                    </button>
                  ))}
                </div>
              </div>
            )}

            <p className="border-t pt-2 font-mono text-[10px] text-muted-foreground">
              {summary.model} · {relativeTime(summary.generatedAt)}
              {summary.basis.chunkCount > 0 && ` · grounded in ${summary.basis.chunkCount} chunks`}
              {summary.cached && ' · cached'}
            </p>
            {activeChat ? (
              <div className="flex gap-1.5">
                <Button
                  variant="outline"
                  size="sm"
                  className="digest-share-cta h-7 min-w-0 flex-1 gap-1.5 text-xs"
                  disabled={sharing}
                  onClick={() => void shareToChat(activeChat.id)}
                  title={`Post the note into “${activeChat.title}”`}
                >
                  {sharing ? <Loader2 className="h-3 w-3 animate-spin" /> : <MessageSquare className="h-3 w-3" />}
                  <span className="truncate">Share to current chat</span>
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="digest-share-cta h-7 w-7 shrink-0 p-0"
                  disabled={sharing}
                  onClick={() => void shareToChat()}
                  aria-label="Share to a new chat"
                  title="Create a dedicated digest chat"
                >
                  <MessageSquarePlus className="h-3 w-3" />
                </Button>
              </div>
            ) : (
              <Button
                variant="outline"
                size="sm"
                className="digest-share-cta h-7 w-full gap-1.5 text-xs"
                disabled={sharing}
                onClick={() => void shareToChat()}
              >
                {sharing ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
                Share to chat
              </Button>
            )}
          </div>
        )}

        {!checked && !generating && !error && (
          <div className="space-y-2">
            <Skeleton className="h-3 w-10/12" />
            <Skeleton className="h-3 w-7/12" />
          </div>
        )}
      </div>
    </div>
  );
}

export function DocumentDetailDialog() {
  const detailDocumentId = useAppStore((s) => s.detailDocumentId);
  const setDetailDocumentId = useAppStore((s) => s.setDetailDocumentId);
  const documents = useAppStore((s) => s.documents);
  const openDocument = useAppStore((s) => s.openDocument);
  const upsertDocument = useAppStore((s) => s.upsertDocument);
  const toggleDocumentStar = useAppStore((s) => s.toggleDocumentStar);

  const [data, setData] = useState<DocumentChunksResponse | null>(null);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [renaming, setRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState('');
  const [renameBusy, setRenameBusy] = useState(false);

  const document = documents.find((d) => d.id === detailDocumentId) ?? null;
  const open = Boolean(detailDocumentId);

  const startRename = () => {
    if (!document) return;
    setRenameValue(document.title);
    setRenaming(true);
  };

  const commitRename = async () => {
    if (!document) return;
    const title = renameValue.trim();
    if (!title || title === document.title) {
      setRenaming(false);
      return;
    }
    setRenameBusy(true);
    try {
      const updated = await renameDocument(document.id, title);
      upsertDocument(updated);
      toast.success(`Renamed to “${title}”`);
      setRenaming(false);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Rename failed');
    } finally {
      setRenameBusy(false);
    }
  };

  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      if (!detailDocumentId) {
        setData(null);
        setPage(1);
        setError(null);
        return;
      }
      setLoading(true);
      setError(null);
      try {
        const res = await fetchDocumentChunks(detailDocumentId, page, 12);
        if (!cancelled) setData(res);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : 'Failed to load chunks');
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    void load();
    return () => {
      cancelled = true;
    };
  }, [detailDocumentId, page]);

  const totalPages = data ? Math.ceil(data.total / data.pageSize) : 1;

  return (
    <Dialog open={open} onOpenChange={(v) => !v && setDetailDocumentId(null)}>
      <DialogContent className="flex max-h-[85vh] flex-col overflow-hidden sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 pr-6">
            <FileText className="h-4 w-4 shrink-0 text-primary" />
            {renaming ? (
              <Input
                value={renameValue}
                disabled={renameBusy}
                onChange={(e) => setRenameValue(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') void commitRename();
                  if (e.key === 'Escape') setRenaming(false);
                }}
                className="h-7 text-sm"
                maxLength={160}
                autoFocus
                aria-label="Edit document title"
              />
            ) : (
              <span className="line-clamp-2 min-w-0 flex-1 sm:line-clamp-none sm:truncate sm:flex-none">
                {document?.title ?? 'Document'}
              </span>
            )}
            {!renaming && (
              <>
                <button
                  type="button"
                  onClick={() => {
                    if (!document) return;
                    toggleDocumentStar(document.id).catch((e) => {
                      toast.error(e instanceof Error ? e.message : 'Could not update star');
                    });
                  }}
                  aria-label={document?.starred ? 'Unstar document' : 'Star document'}
                  aria-pressed={document?.starred}
                  className="shrink-0 rounded-sm p-0.5 transition-all hover:scale-125 active:scale-95"
                >
                  <Star
                    className={
                      document?.starred
                        ? 'h-3.5 w-3.5 fill-amber-400 text-amber-400'
                        : 'h-3.5 w-3.5 text-muted-foreground transition-colors hover:text-amber-400'
                    }
                  />
                </button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 shrink-0 text-muted-foreground hover:text-foreground"
                  onClick={startRename}
                  aria-label="Rename document"
                >
                  <Pencil className="h-3 w-3" />
                </Button>
              </>
            )}
            {renaming && (
              <Button
                variant="ghost"
                size="sm"
                className="h-6 shrink-0 px-2 text-xs"
                disabled={renameBusy}
                onClick={() => void commitRename()}
              >
                {renameBusy ? <Loader2 className="h-3 w-3 animate-spin" /> : 'Save'}
              </Button>
            )}
          </DialogTitle>
          <DialogDescription className="truncate">{document?.fileName}</DialogDescription>
        </DialogHeader>

        {document && (
          <div className="grid grid-cols-2 gap-2 rounded-xl border bg-muted/30 p-3 text-xs sm:grid-cols-4">
            <div>
              <p className="text-muted-foreground">Pages</p>
              <p className="font-mono text-sm font-semibold">{document.pageCount || '—'}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Chunks</p>
              <p className="font-mono text-sm font-semibold">{data?.total ?? document.chunkCount}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Tokens</p>
              <p className="font-mono text-sm font-semibold">{document.tokenCount.toLocaleString()}</p>
            </div>
            <div>
              <p className="text-muted-foreground">Size</p>
              <p className="font-mono text-sm font-semibold">{formatBytes(document.fileSize)}</p>
            </div>
            {document.ocrPages > 0 && (
              <div className="col-span-2 flex items-center gap-1.5 rounded-lg border border-cyan-500/25 bg-cyan-500/[0.07] px-2 py-1.5 sm:col-span-4">
                <ScanLine className="h-3.5 w-3.5 shrink-0 text-cyan-500" aria-hidden />
                <p className="text-[11px] leading-snug text-cyan-700 dark:text-cyan-300">
                  <span className="font-semibold">OCR-recovered document</span> — the text layer was
                  reconstructed by recognizing {document.ocrPages} scanned page{document.ocrPages === 1 ? '' : 's'}.
                  Answers may contain recognition artifacts.
                </p>
              </div>
            )}
          </div>
        )}

        {document && (
          <div className="flex flex-wrap items-center gap-1.5">
            <TagEditor
              doc={document}
              suggestions={documents
                .flatMap((d) => d.tags)
                .filter((t, i, arr) => arr.indexOf(t) === i && !document.tags.includes(t))}
              onSaved={upsertDocument}
              className="h-6 w-6"
            />
            {document.tags.length === 0 ? (
              <span className="text-[11px] text-muted-foreground">No tags — add context for filtering.</span>
            ) : (
              document.tags.map((tag) => (
                <span
                  key={tag}
                  className="doc-tag rounded-full border border-primary/25 bg-primary/5 px-2 py-0.5 text-[10px] font-medium text-primary"
                >
                  {tag}
                </span>
              ))
            )}
          </div>
        )}

        {document && (
          <DigestSection
            key={document.id}
            documentId={document.id}
            title={document.title}
            indexed={document.status === 'COMPLETED' && document.chunkCount > 0}
          />
        )}

        <div className="mb-1 flex items-center gap-2">
          <Layers className="h-3.5 w-3.5 text-primary/70" />
          <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Vector index contents
          </span>
          <div className="ml-auto flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              disabled={page <= 1 || loading}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              aria-label="Previous chunks page"
            >
              <ChevronLeft className="h-3.5 w-3.5" />
            </Button>
            <span className="font-mono text-[11px] text-muted-foreground">
              {page} / {totalPages}
            </span>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              disabled={page >= totalPages || loading}
              onClick={() => setPage((p) => p + 1)}
              aria-label="Next chunks page"
            >
              <ChevronRight className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        <ScrollArea className="insightdoc-scroll -mx-1 min-h-0 flex-1 px-1">
          {loading && (
            <div className="flex justify-center py-8">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          )}
          {error && <p className="py-6 text-center text-sm text-destructive">{error}</p>}
          {!loading && !error && data && (
            <div className="space-y-2 pb-2">
              {data.chunks.length === 0 && (
                <p className="py-6 text-center text-xs text-muted-foreground">
                  No chunks indexed for this document.
                </p>
              )}
              {data.chunks.map((c: ChunkPreview) => (
                <div key={c.id} className="rounded-lg border bg-card/60 p-3">
                  <div className="mb-1.5 flex items-center gap-2">
                    <Badge variant="outline" className="gap-1 px-1.5 font-mono text-[10px]">
                      <MapPin className="h-2.5 w-2.5" /> p.{c.pageNumber}
                    </Badge>
                    <span className="font-mono text-[10px] text-muted-foreground">chunk #{c.chunkIndex}</span>
                    {c.tokenCount !== null && (
                      <span className="font-mono text-[10px] text-muted-foreground">· {c.tokenCount} tok</span>
                    )}
                    <Button
                      variant="ghost"
                      size="sm"
                      className="ml-auto h-6 gap-1 px-2 text-[11px] text-primary"
                      onClick={() => {
                        setDetailDocumentId(null);
                        openDocument(document!.id, c.pageNumber);
                      }}
                    >
                      View page
                    </Button>
                  </div>
                  {c.heading && (
                    <p className="mb-1 truncate text-[11px] font-medium text-primary/80" title={c.heading}>
                      § {c.heading}
                    </p>
                  )}
                  <p className="line-clamp-4 text-xs leading-relaxed text-muted-foreground">{c.preview}</p>
                </div>
              ))}
            </div>
          )}
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
